version: "2"

linters:
  timeout: 5m
  relative-path-mode: gomod
  build-tags:
    - main
    - postgres
  disable-all: true
  enabled:
    - errcheck
    - exhaustive
    - gocritic
    - goimports
    - govet
    - inamedparam
    - ireturn
    - misspell
    - nakedret
    - nolintlint
    - perfsprint
    - reassign
    - staticcheck
    - wrapcheck
    # not configured
    - makezero
    - rowserrcheck
    - ineffassign
    - asaslint
    - bodyclose
    - canonicalheader
    - copyloopvar
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exptostd
    - fatcontext
    - gocheckcompilerdirectives
    - gochecknoglobals
    - godox
    - gomoddirectives
    - goprintffuncname
    - gosec
    - iface
    - intrange
    - mirror
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - predeclared
    - recvcheck
    - sqlclosecheck
    - testifylint
    - testpackage
    - unconvert
    - unparam
    - usedstdlibvars
    - wastedassign
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    exhaustive:
      check:
        - switch
        - map
      default-case-required: true
    goimports:
      local-prefixes: go.openly.dev
    govet:
      enable-all: true
      disable:
        - fieldalignment
      settings:
        shadow:
          strict: true
    inamedparam:
      skip-single-param: true
    ireturn:
      allow:
        - anon
        - empty      
        - error
        - generic
        - stdlib
        - trace.Span
        - trace.Tracer
        - (or|er)$
    misspell:
      mode: restricted
    nakedret:
      max-func-lines: 10
    nolintlint:
      require-explanation: true
      require-specific: true
    perfsprint:
      strconcat: false
    reassign:
      patterns:
        - ".*"
    staticcheck:
      checks: [ "all" ]
    wrapcheck:
      ignoreSigs:
        - .Errorf(
        - errors.New(
        - errors.Newf(
        - errors.Unwrap(
        - errors.Join(
        - errors.Wrap(
        - errors.Wrapf(
        - (context.Context).Err()

formatters:
  enable:
    - gofumpt
    - goimports
